##############################################################################
#
#   Controller communication information
#
##############################################################################

ip_addr: 172.22.18.70
http_port: 8181
admin_name: "admin"
admin_pswd: "admin"
