##############################################################################
#
#   Controller communication information
#
##############################################################################

ip_addr: 10.3.21.113 
http_port: 8181
admin_name: "admin"
admin_pswd: "admin"
