##############################################################################
#
#   NETCONF devices communication information
#
##############################################################################

name: "vRouter"
ip_addr: 172.22.17.110
port: 830
admin_name: "vyatta"
admin_pswd: "vyatta"
