###############################################################################
#
#   List of NETCONF devices to communicate with
#
##############################################################################

# NETCONF device 1
- name: "Router1"
  ip_addr: 10.30.30.1
  port: 830
  admin_name: "cisco"
  admin_pswd: "cisco"

# NETCONF device 2
#- name: "Router2"
#  ip_addr: 10.0.0.2
#  port: 830
#  admin_name: "cisco"
#  admin_pswd: "cisco"

# NETCONF device 3
#- name: "Router3"
#  ip_addr: 10.0.0.3
#  port: 830
#  admin_name: "cisco"
#  admin_pswd: "cisco"
