##############################################################################
#
#   List of NETCONF devices to communicate with
#
##############################################################################

# NETCONF device 1
- name: "vRouter"
  ip_addr: 172.22.17.110
  port: 830
  admin_name: "vyatta"
  admin_pswd: "vyatta"

# NETCONF device 2
- name: "NC_DEV-2"
#- name: "vRouter"
  ip_addr: 10.30.30.2
  port: 830
  admin_name: "admin"
  admin_pswd: "cisco"

# NETCONF device 3
- name: "NC_DEV-3"
#- name: "vRouter"
#  ip_addr: 10.30.30.3
  ip_addr: 172.22.17.110
  port: 830
  admin_name: "vyatta"
  admin_pswd: "vyatta"
